index:
    path: /
    controller: App\Controller\AccueilController::index


login:
    path: /login
    controller: App\Controller\LoginController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

reservation:
    path: /reservation
    controller: App\Controller\ReservationController::index

panier:
    path: /panier
    controller: App\Controller\PanierController::index

confirmation:
    path: /confirm
    controller: App\Controller\ConfirmationController::index